saving transaction data in db
KarlaOg/PA_ESGI_4IW3 pull request #92
Opened 2021-07-02 20:56 UTC by aitamara

2021-07-04 14:55 UTC, moussia reviewed
essaie de supprimer les consol.log mais tout est nikel.

2021-07-04 18:02 UTC, askemeline commented
est ce qu'il y a aussi la securiter des url du paiement ?

2021-07-04 18:08 UTC, askemeline requested changes
Il faut une seule migration pas deux. On va avoir des soucis de notre coter sur la prod

2021-07-04 18:41 UTC, askemeline commented
<img width="855" alt="Screenshot 2021-07-04 at 20 41 31" src="https://user-images.githubusercontent.com/33722860/124396149-385c9300-dd08-11eb-9e97-76f25d0a9c93.png">

besoin que d'une seule migration

2021-07-04 19:28 UTC, askemeline commented
Si on clique sur l'url https://localhost:8000/detail-paiment ou sucess ou les autres url de paiment ss avoir valider un influencueur on peut quand meme cliquer dessus, a securiser

2021-07-06 20:47 UTC, askemeline approved these changes

2021-07-08 18:53 UTC, merged