Espace commentaire
KarlaOg/PA_ESGI_4IW3 pull request #93
Opened 2021-07-02 21:29 UTC by YanisF6

** Sur le détail d'une offre :
-  Influenceur : j'ai la possibilité d'ajouter un commentaire ou de répondre à un commentaire
- Marque : j'ai la possibilité de répondre à un commentaire
- Une fois le commentaire envoyé, la marque reçoit une notification par mail.

** Pensez à mettre à jour la DB

** Je vais ajouter des fixtures pour les commentaires

2021-07-03 00:01 UTC, KarlaOg commented
J'ai mis du JS dans ton input et le JS a ete exécuter 
![image](https://user-images.githubusercontent.com/33722964/124337253-ebf74300-dba1-11eb-9691-9d0441828572.png)
On peut pas merger sa deja c'est pas un feature du cahier surtout avec cette faille
Adrien l'avait dit la dernière fois il allait tester nos inputs avec du JS pour les failles

2021-07-03 00:03 UTC, KarlaOg requested changes
### WITH SECURITY ###

2021-07-03 00:13 UTC, aitamara commented
Faut mettre une condition pour ne pas afficher les commentaires si il n'y a aucun commentaire
<img width="1096" alt="Screenshot 2021-07-03 at 02 12 43" src="https://user-images.githubusercontent.com/49433308/124337709-4a252580-dba4-11eb-997e-92617793bc0f.png">

2021-07-03 09:56 UTC, YanisF6 commented
J'ai déjà mis une condition pour afficher seulement les commentaires qui existent, dans ton cas mohand l'utilisateur n'a pas de firstname, c'est au niveau de l'inscription normalement firstname et lastname doivent être requis sauf que là c'est pas le cas, je vais modifier ça 
![image](https://user-images.githubusercontent.com/46170340/124350573-ac5a4680-dbf5-11eb-9383-047b6fabc79b.png)

2021-07-03 14:21 UTC, YanisF6 commented
C'est fix le problème @KarlaOg

2021-07-04 15:35 UTC, moussia approved these changes
de mon coté, le js ne passe pas, il y a un message d'erreur. ca m'a l'air bien.

2021-07-04 17:49 UTC, askemeline commented on templates/offer/show.html.twig
> +{% block javascripts %}
ou est le prant ? ca va pas marcher tailwind si tu appel pas le js de base.html

2021-07-04 17:50 UTC, askemeline commented on templates/offer/show.html.twig
> +			{% endfor %}<hr></div><link rel="stylesheet" href="{{ asset('css/comments.css') }}"/><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link
est)ce que le fichier comments.css est mifier dans webpack ? non soit tu modife la contif ou alors tu le mets dans app.scc sinon le site va etre encore plus lent

2021-07-04 17:52 UTC, askemeline commented on README.md
> +php bin/console doctrine:schema:update --dump-sql
pas besoin de ca pcq les migrations qu'on a sur develop sont clean

2021-07-04 17:55 UTC, askemeline requested changes
Le bouton repondre ne marche pas.

2021-07-04 17:56 UTC, askemeline commented
<img width="1401" alt="Screenshot 2021-07-04 at 19 55 50" src="https://user-images.githubusercontent.com/33722860/124394931-d8fb8480-dd01-11eb-9183-2bacf19d5d5e.png">
ca marche une fois sur 2
Probleme de fixture peut etre ?

2021-07-04 17:57 UTC, askemeline commented
pas du tout bon a merger

2021-07-05 10:06 UTC, YanisF6 commented on templates/offer/show.html.twig
> +			{% endfor %}<hr></div><link rel="stylesheet" href="{{ asset('css/comments.css') }}"/><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link
je l'ajoute à webpack alors

2021-07-05 10:07 UTC, YanisF6 commented
Pour firstname c'est un problème de fixture je pense, car l'utilisateur doit avoir forcément un firstname

2021-07-05 10:10 UTC, askemeline commented on templates/offer/show.html.twig
> +			{% endfor %}<hr></div><link rel="stylesheet" href="{{ asset('css/comments.css') }}"/><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link
par conte ton atchitecture ca va pas le dossier ou est le fichier scss est ici /assets/styles/
donc il faut bouger ca ici

2021-07-05 10:16 UTC, YanisF6 commented
Pour le bouton répondre, tu click dessus ensuite tu ajoute ton message sur le section au dessus, (comme c'est au même niveau sur la page, tu vois pas que le bouton te redirige sur la section commentaire, mais si tu as bcp de commentaire et tu scroll vers les derniers (bas de la page), quand tu click sur répondre il te redirige bien au dessus)
![image](https://user-images.githubusercontent.com/46170340/124456175-b2356080-dd8a-11eb-8562-366e71b4cab6.png)

2021-07-05 10:18 UTC, askemeline commented
ca n'a pas scroller de mon côté, je trouve pas ca tres ui

2021-07-05 10:19 UTC, askemeline commented
oui je pense que tu as un soucis de fixture d'ou ce message d'erreur

2021-07-05 10:32 UTC, YanisF6 commented on templates/offer/show.html.twig
> +			{% endfor %}<hr></div><link rel="stylesheet" href="{{ asset('css/comments.css') }}"/><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"><link
Ok ça marche

2021-07-06 10:45 UTC, aitamara approved these changes

2021-07-07 14:19 UTC, KarlaOg commented
Est ce que coté admin on peut delete les comments qui sont relier a un offre ? 
<img width="1183" alt="Capture d’écran 2021-07-07 à 16 17 47" src="https://user-images.githubusercontent.com/33722964/124775738-29135a80-df3f-11eb-90b6-44d09f8116f7.png">

2021-07-07 14:25 UTC, YanisF6 commented
Non j'avais pas pensé à ça, merci de me l'avoir fait remarquer !

2021-07-28 21:30 UTC, merged